type People = Array<{
    name: string
    /** Abbreviation generated by Onenote */
    abbreviation?: string
    role: string
    otherRoles?: string
}>
const people: People = [
    { name: "Fiona Fung", abbreviation: "FF", role: "Manager, 2010-2015", otherRoles: "JS thru Oct 2012, JS/TS afterward" },
    { name: "Joe Pamer" , abbreviation: "JP" , role: "Dev Lead, 2011-2014" , otherRoles: "F# Dev Lead, Apple Languages Dev Manager" },
    { name: "Paul van Brenk", abbreviation: "PvB", role: "Engineer, 201x-2017", },
    { name: "Sheetal Nandi", abbreviation: "SN" , role: "Engineer, 2010-present", otherRoles: "JS thru X 201x, TS afterward" },
    { name: "Jason Freeman", abbreviation: "JF", role: "Engineer, 201x-2015", },
    { name: "Jonathan Turner", abbreviation: "JT" , role: "Program Manager, 2012-2015", otherRoles: "Rust PM afterward" },
    { name: "Mohamed Hegazy", abbreviation: "MH" , role: "Dev Lead, 2013-2018", otherRoles: "JSTS lead thru 2014?" }, 
    { name: "Dan Quirk", abbreviation: "DQ" , role: "Engineer, 201x-2015", otherRoles: "JSTS before? Testing before?" }, 
    { name: "Robin Zhu", abbreviation: "RZ" , role: "??", otherRoles: "Vendor from Wicresoft?" }, 
    { name: "Luke Hoban", abbreviation: "LH", role: "Engineer, 2011-201x", },
    { name: "Ryan Cavanaugh", abbreviation: "RC" , role: "Dev Lead, 2018-present", otherRoles: "Engineer, 2012-2018" }, 
    { name: "Bill Ticehurst", abbreviation: "BT", role: "Dev Lead JS/TS, 2012-2018", otherRoles: "Test 2012-2014, JS/TS afterward" },
    { name: "Alice Liu", abbreviation: "ALC", role: "??", otherRoles: "Vendor from Beyondsoft?" },
]
function generateTable() {
    console.log("# People #")
    console.log()
    console.log("|Name|Abbreviation|Role|Other Roles|")
    console.log("|----|------------|----|-----------|")
    for (const p of people) {
        console.log("|" + [p.name, p.abbreviation, p.role, p.otherRoles].join("|") + "|")
    }
}
generateTable()