type People = Array<{
  name: string;
  /** Abbreviation generated by Onenote */
  abbreviation?: string;
  role: string;
  otherRoles?: string;
}>;
const people: People = [
  {
    name: "Fiona Fung",
    abbreviation: "FF",
    role: "Manager, 2010-2015",
    otherRoles: "JS thru Oct 2012, JS/TS afterward",
  },
  {
    name: "Joe Pamer",
    abbreviation: "JP",
    role: "Dev Lead, 2011-2014",
    otherRoles: "F# Dev Lead, Apple Languages Dev Manager",
  },
  { name: "Paul van Brenk", abbreviation: "PvB", role: "Engineer, 201x-2017" },
  {
    name: "Sheetal Nandi",
    abbreviation: "SN",
    role: "Engineer, 2010-present",
    otherRoles: "JS thru X 201x, TS afterward",
  },
  { name: "Jason Freeman", abbreviation: "JF", role: "Engineer, 201x-2015" },
  {
    name: "Jonathan Turner",
    abbreviation: "JT",
    role: "Program Manager, 2012-2015",
    otherRoles: "Rust PM afterward",
  },
  {
    name: "Mohamed Hegazy",
    abbreviation: "MH",
    role: "Dev Lead, 2013-2018",
    otherRoles: "JSTS lead thru 2014?",
  },
  {
    name: "Dan Quirk",
    abbreviation: "DQ",
    role: "Engineer, 201x-2015",
    otherRoles: "JSTS before? Testing before?",
  },
  {
    name: "Robin Zhu",
    abbreviation: "RZ",
    role: "??",
    otherRoles: "Vendor from Wicresoft?",
  },
  {
    name: "Luke Hoban",
    abbreviation: "LH",
    role: "Engineer, 2011-201x",
    otherRoles: "Sometimes abbreviated LJH or L",
  },
  {
    name: "Ryan Cavanaugh",
    abbreviation: "RC",
    role: "Dev Lead, 2018-present",
    otherRoles: "Engineer, 2012-2018",
  },
  {
    name: "Bill Ticehurst",
    abbreviation: "BT",
    role: "Dev Lead JS/TS, 2012-2018",
    otherRoles: "Test 2012-2014, JS/TS afterward",
  },
  {
    name: "Alice Liu",
    abbreviation: "ALC",
    role: "??",
    otherRoles: "Vendor from Beyondsoft?",
  },
  {
    name: "Uladzimir Matsveyeu",
    abbreviation: "UM",
    role: "Engineer, 2014-2017",
    otherRoles:
      "F# engineer through 2013, Facebook language engineer afterward",
  },
  {
    name: "Gearard Boland",
    abbreviation: "GB",
    role: "??",
    otherRoles: "Group Engineering Manager afterward",
  },
  {
    name: "Gabriel Esparza-Romero",
    abbreviation: "GE",
    role: "Test Manager?",
    otherRoles: "Group Engineering Manager",
  },
  {
    name: "Cyrus Najmabadi",
    abbreviation: "CN",
    role: "Engineer, 201?-2015",
    otherRoles: "C# Engineer before and after",
  },
  { name: "Brian Terlson", abbreviation: "BT", role: "TC39 Editor" },
  {
    name: "Hani Atassi",
    abbreviation: "HA",
    role: "??",
    otherRoles: "VS Mobile Tooling, then Facebook after",
  },
  {
    name: "Rob Lourens",
    abbreviation: "RL",
    role: "F12 Engineer, 2014-2016",
    otherRoles: "VS Code afterward",
  },
  { name: "Richard Hua", abbreviation: "RH", role: "F12 Engineer, 2014-2017" },
  { name: "Peter Yu", abbreviation: "PY", role: "??" },
  {
    name: "Shishir Horane",
    abbreviation: "SH",
    role: "F12 Engineer, 2013-2015",
  },
  { name: "Michael Booth", abbreviation: "MB", role: "??" },
  { name: "Bowden Kelly", abbreviation: "BK", role: "PM, 2015-2017" },
  { name: "Dirk Baeumer", abbreviation: "DB", role: "VS Code Engineer" },
  { name: "Anders Hejlsberg", abbreviation: "AH", role: "Technical Fellow" },
  { name: "Steve Lucco", abbreviation: "SteveLuc", role: "Technical Fellow" },
  { name: "Mads Torgersen", abbreviation: "MadsT", role: "C# PM" },
  { name: "ChuckJ", role: "??" },
  { name: "ToddPro", role: "??" },
  { name: "JoshWil", role: "??" },
];
function generateTable() {
  console.log("# People #");
  console.log();
  console.log("|Name|Abbreviation|Role|Other Roles|");
  console.log("|----|------------|----|-----------|");
  for (const p of people) {
    console.log(
      "|" + [p.name, p.abbreviation, p.role, p.otherRoles].join("|") + "|",
    );
  }
}
generateTable();
